python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_0_balanced --fold 0 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_1_balanced --fold 1 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_2_balanced --fold 2 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_3_balanced --fold 3 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_4_balanced --fold 4 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_5_balanced --fold 5 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_6_balanced --fold 6 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_7_balanced --fold 7 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_8_balanced --fold 8 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
python3 /send/fdgClass/pp/code/classify.py --gpu_ids 2,3 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 7 --name 7class_9_balanced --fold 9 --n_epochs 10 --n_epochs_decay 190 --lr 0.00001 --batchSize 48 --depthSize 512 --model SEResNext101 --aug --class7
#gpu 3개시 batch 64
python3 /send/fdgClass/pp/code/gradcam.py --name 4class_SeRext101_0_aug --fold 0 --dataroot /send/fdgClass/pp/sevJoint --checkpoints_dir /send/fdgClass/pp/log --input_nc 3 --output_nc 2 --depthSize 512